export const CLIENT_REPOSITORY = 'CLIENT_REPOSITORY';
export const AUTHORIZATION_CODE_REPOSITORY = 'AUTHORIZATION_CODE_REPOSITORY';
export const REFRESH_TOKEN_REPOSITORY = 'REFRESH_TOKEN_REPOSITORY';
export const SIGNER = 'SIGNER';
