FROM node:20-slim

WORKDIR /repo

RUN corepack enable

RUN apt-get update && apt-get install -y openssl

COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./

COPY apps/web-ui/package.json apps/web-ui/package.json

RUN pnpm install --frozen-lockfile

COPY . .

CMD ["pnpm", "-C", "apps/web-ui", "dev"]